--- !pipeline
save_intermediate: True
skip_gfp_gan: True
skip_domain_mixup: True
skip_segmentation: False
skip_depth_segmentation: True

--- !e4e
transformations: []

--- !translation
use_precomputed: True
use_characs_in_img: False

--- !gfp_gan
upscale: 2
bg_tile: 400
margin: 6
transformations: []

--- !domain_mixup
recompute_dist: False
margin: 42

--- !segmentation
margin: 21
foreground_margin: 6
avoid_transformations: ['N_max']

--- !depth_segmentation
foreground_coef: 8.0
transformations: ['all']
