save_path: 'configs/runs/e4e_nogfp'

projection_dir: 'projection/50_itr'
result_dir: 'res/e4e_nogfp'

e4e.transformations: ["A", "B", "Bald", "Bn", "Bp", "Ch", "D", "Hc", "Pn", "Se"]
translation.use_characs_in_img: True
translation.use_precomputed: True
pipeline.save_intermediate: True
pipeline.skip_depth_segmentation: True
pipeline.skip_gfp_gan: True
