save_path: 'configs/runs/not_e4e_nogfp'

projection_dir: 'projection/50_itr'
result_dir: 'res/not_e4e_nogfp'

e4e.transformations: []
translation.use_characs_in_img: True
translation.use_precomputed: True
pipeline.save_intermediate: True
pipeline.skip_depth_segmentation: True
pipeline.skip_gfp_gan: True
