name: Isort

on: [push]

jobs:
  isort-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: isort/isort-action@master
        with:
            requirementsFiles: "requirements.txt"
