

name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install anybadge
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc --disable=import-error --output-format=text $(git ls-files '*.py') | tee pylint.txt
    - name: Create badge for pylint
      run: |
        score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
        color=$(python .badge/pylint_get_color.py --score=$score)
        echo "Pylint score was $score"
        echo "PYLINT_COLOR=$color"
        echo "PYLINT_COLOR=$color" >> $GITHUB_ENV
        echo "PYLINT_SCORE=$score/10.00"
        echo "PYLINT_SCORE=$score/10.00" >> $GITHUB_ENV
    - name: Create Pylint Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: c60e6ce49447254be085193c99b8425b
        filename: pylint_badge.json
        label: pylint
        message: ${{ env.PYLINT_SCORE }}
        color: ${{ env.PYLINT_COLOR }}
        style: flat
