

name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install anybadge
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc --disable=import-error --output-format=text $(git ls-files '*.py') | tee pylint.txt
    - name: Create badge for pylint
      run: |
        score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
        echo "Pylint score was $score"
        anybadge --value=$score --file=.badge/pylint.svg -o --label=pylint 2=red 4=orange 7=yellow 9=green
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pylint_badge
        path: .badge/pylint.svg
        retention-days: 10000
